#!/usr/bin/env bash
set -euo pipefail

# Partition and format a 500GB UEFI/GPT disk for Debian.
# Layout:
#   1) EFI (512 MiB) -> /boot/efi
#   2) root (30 GiB) -> /
#   3) var (40 GiB) -> /var
#   4) var_log (8 GiB) -> /var/log
#   5) data (rest) -> /srv/data
#
# Usage:
#   sudo ./scripts/partition-uefi-500g.sh /dev/nvme0n1 [/mnt/target]

DEV="${1:-}"
MOUNT_ROOT="${2:-/mnt/target}"

if [[ -z "$DEV" ]]; then
  echo "Usage: $0 /dev/nvme0n1 [/mnt/target]" >&2
  exit 1
fi

if [[ ! -b "$DEV" ]]; then
  echo "Error: $DEV is not a block device." >&2
  exit 1
fi

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Error: run as root." >&2
  exit 1
fi

echo "About to ERASE and re-partition: $DEV"
lsblk -o NAME,SIZE,TYPE,MOUNTPOINT "$DEV"
echo
read -r -p "Type YES to continue: " confirm
if [[ "$confirm" != "YES" ]]; then
  echo "Aborted."
  exit 1
fi

echo "Unmounting any mounted partitions on $DEV..."
mapfile -t MOUNTS < <(lsblk -ln -o MOUNTPOINT "$DEV" | awk 'NF')
for mp in "${MOUNTS[@]}"; do
  umount "$mp"
done

echo "Wiping existing signatures..."
if command -v sgdisk >/dev/null 2>&1; then
  sgdisk --zap-all "$DEV"
fi
wipefs -a "$DEV"

EFI_SIZE_MIB=512
ROOT_SIZE_MIB=$((30 * 1024))
VAR_SIZE_MIB=$((40 * 1024))
VARLOG_SIZE_MIB=$((8 * 1024))

EFI_START_MIB=1
EFI_END_MIB=$((EFI_START_MIB + EFI_SIZE_MIB))
ROOT_START_MIB=$EFI_END_MIB
ROOT_END_MIB=$((ROOT_START_MIB + ROOT_SIZE_MIB))
VAR_START_MIB=$ROOT_END_MIB
VAR_END_MIB=$((VAR_START_MIB + VAR_SIZE_MIB))
VARLOG_START_MIB=$VAR_END_MIB
VARLOG_END_MIB=$((VARLOG_START_MIB + VARLOG_SIZE_MIB))

echo "Creating GPT partitions..."
parted -s -a optimal "$DEV" mklabel gpt
parted -s -a optimal "$DEV" mkpart ESP fat32 "${EFI_START_MIB}MiB" "${EFI_END_MIB}MiB"
parted -s -a optimal "$DEV" set 1 esp on
parted -s -a optimal "$DEV" name 1 EFI
parted -s -a optimal "$DEV" mkpart root ext4 "${ROOT_START_MIB}MiB" "${ROOT_END_MIB}MiB"
parted -s -a optimal "$DEV" name 2 OS_ROOT
parted -s -a optimal "$DEV" mkpart var ext4 "${VAR_START_MIB}MiB" "${VAR_END_MIB}MiB"
parted -s -a optimal "$DEV" name 3 OS_VAR
parted -s -a optimal "$DEV" mkpart varlog ext4 "${VARLOG_START_MIB}MiB" "${VARLOG_END_MIB}MiB"
parted -s -a optimal "$DEV" name 4 OS_VARLOG
parted -s -a optimal "$DEV" mkpart data ext4 "${VARLOG_END_MIB}MiB" 100%
parted -s -a optimal "$DEV" name 5 DATA

partprobe "$DEV"
udevadm settle

if [[ "$DEV" =~ [0-9]$ ]]; then
  PART_PREFIX="${DEV}p"
else
  PART_PREFIX="$DEV"
fi

EFI_PART="${PART_PREFIX}1"
ROOT_PART="${PART_PREFIX}2"
VAR_PART="${PART_PREFIX}3"
VARLOG_PART="${PART_PREFIX}4"
DATA_PART="${PART_PREFIX}5"

echo "Formatting filesystems..."
mkfs.fat -F32 -n EFI "$EFI_PART"
mkfs.ext4 -F -L OS_ROOT "$ROOT_PART"
mkfs.ext4 -F -L OS_VAR "$VAR_PART"
mkfs.ext4 -F -L OS_VARLOG "$VARLOG_PART"
mkfs.ext4 -F -L DATA -m 0 "$DATA_PART"

echo "Mounting at $MOUNT_ROOT..."
mkdir -p "$MOUNT_ROOT"
mount "$ROOT_PART" "$MOUNT_ROOT"
mkdir -p "$MOUNT_ROOT/boot/efi" "$MOUNT_ROOT/var" "$MOUNT_ROOT/var/log" "$MOUNT_ROOT/srv/data"
mount "$VAR_PART" "$MOUNT_ROOT/var"
mount "$VARLOG_PART" "$MOUNT_ROOT/var/log"
mount "$DATA_PART" "$MOUNT_ROOT/srv/data"
mount "$EFI_PART" "$MOUNT_ROOT/boot/efi"

ROOT_UUID="$(blkid -s UUID -o value "$ROOT_PART")"
VAR_UUID="$(blkid -s UUID -o value "$VAR_PART")"
VARLOG_UUID="$(blkid -s UUID -o value "$VARLOG_PART")"
DATA_UUID="$(blkid -s UUID -o value "$DATA_PART")"
EFI_UUID="$(blkid -s UUID -o value "$EFI_PART")"

FSTAB_PATH="$MOUNT_ROOT/etc/fstab.generated"
mkdir -p "$MOUNT_ROOT/etc"
cat > "$FSTAB_PATH" <<EOF
# /etc/fstab entries generated by partition-uefi-500g.sh
UUID=$ROOT_UUID  /          ext4  defaults,noatime,errors=remount-ro  0 1
UUID=$VAR_UUID   /var       ext4  defaults,noatime                   0 2
UUID=$VARLOG_UUID /var/log  ext4  defaults,noatime                   0 2
UUID=$DATA_UUID  /srv/data  ext4  defaults,noatime                   0 2
UUID=$EFI_UUID   /boot/efi  vfat  umask=0077                         0 1
EOF

echo "Done."
echo "Generated fstab: $FSTAB_PATH"
