#!/usr/bin/env bash
set -euo pipefail
umask 022

OUT_DIR="/etc/ovr/telegraf.d"
OUT_FILE="${OUT_DIR}/gx_mqtt_sources.conf"

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: missing required command: $1" >&2
    exit 1
  fi
}

need_cmd avahi-browse

mkdir -p "${OUT_DIR}"

declare -A seen
declare -a brokers

while IFS=';' read -r _ iface proto name type domain host addr port rest; do
  [ "${proto}" = "IPv4" ] || continue
  [ "${port}" = "1883" ] || continue

  system_id="${host%.local}"
  ip="${addr}"
  key="${system_id}|${ip}"
  if [ -n "${seen[$key]:-}" ]; then
    continue
  fi

  if command -v nc >/dev/null 2>&1; then
    if ! nc -z -w 2 "${ip}" 1883 >/dev/null 2>&1; then
      continue
    fi
  fi

  seen["$key"]=1
  brokers+=("${system_id}|${ip}")
done < <(avahi-browse -rtp _mqtt._tcp 2>/dev/null | awk -F';' 'NF>=9 {print}')

tmp_file="$(mktemp)"
{
  echo "# Auto-generated by ovr-refresh-gx-mqtt-sources. Do not edit."
  echo "# Source: avahi-browse _mqtt._tcp (IPv4)"
  echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""

  if [ "${#brokers[@]}" -eq 0 ]; then
    echo "# No MQTT brokers discovered."
  else
    for entry in "${brokers[@]}"; do
      system_id="${entry%%|*}"
      ip="${entry##*|}"
      cat <<EOF
[[inputs.mqtt_consumer]]
  servers = ["tcp://${ip}:1883"]
  topics = ["N/#"]
  qos = 0
  connection_timeout = "5s"
  client_id = "ovr-${system_id}"
  data_format = "json"
  topic_tag = "topic"
  tags = { system_id = "${system_id}", gx_host = "${ip}" }

EOF
    done
  fi
} > "${tmp_file}"

mv "${tmp_file}" "${OUT_FILE}"
chmod 0644 "${OUT_FILE}"
