#!/usr/bin/env bash
set -euo pipefail
umask 022

EDGE_DIR="${EDGE_DIR:-/opt/ovr/edge}"
OVR_DIR="${OVR_DIR:-/etc/ovr}"

OUT_DIR="${OVR_DIR}/telegraf.d"
OUT_FILE="${OUT_DIR}/gx_mqtt_sources.conf"
LIST="${OVR_DIR}/targets_gx.txt"

# Fallback to repo file if not in /etc/ovr
if [ ! -f "${LIST}" ]; then
  LIST="${EDGE_DIR}/telegraf/targets_gx.txt"
fi

if [ ! -f "${LIST}" ]; then
  echo "ERROR: Missing GX targets list ${LIST}" >&2
  exit 1
fi

mkdir -p "${OUT_DIR}"

# Check if MQTT port is reachable
mqtt_reachable() {
  local ip="$1"
  timeout 1 bash -c "cat < /dev/null > /dev/tcp/${ip}/1883" 2>/dev/null
}

# Discover portal ID by subscribing to system serial
discover_portal_id() {
  local ip="$1"
  local portal_id=""

  if command -v mosquitto_sub >/dev/null 2>&1; then
    # Subscribe briefly to get the portal ID from system serial
    portal_id=$(timeout 3 mosquitto_sub -h "${ip}" -t 'N/+/system/0/Serial' -C 1 2>/dev/null | \
      sed -n 's/.*"value":"\([^"]*\)".*/\1/p' || true)
  fi

  echo "${portal_id}"
}

# Send keepalive to GX device
send_keepalive() {
  local ip="$1"
  local portal_id="$2"

  if [ -z "${portal_id}" ]; then
    return 1
  fi

  if command -v mosquitto_pub >/dev/null 2>&1; then
    mosquitto_pub -h "${ip}" -t "R/${portal_id}/keepalive" -m '' 2>/dev/null && \
      echo "KEEPALIVE sent to ${portal_id} (${ip})" || \
      echo "KEEPALIVE failed for ${portal_id} (${ip})"
  else
    echo "WARN: mosquitto_pub not installed, cannot send keepalive"
  fi
}

declare -a brokers
added=0
skipped=0

while read -r hostname; do
  # Skip empty lines and comments
  [[ -z "${hostname}" ]] && continue
  [[ "${hostname}" =~ ^# ]] && continue

  # Resolve mDNS hostname to IP
  fqdn="${hostname}.local"
  ip=$(getent hosts "${fqdn}" 2>/dev/null | awk '{print $1}' | head -1)

  if [ -z "${ip}" ]; then
    echo "SKIP ${hostname}: hostname not resolvable"
    skipped=$((skipped+1))
    continue
  fi

  if ! mqtt_reachable "${ip}"; then
    echo "SKIP ${hostname} (${ip}): MQTT not reachable"
    skipped=$((skipped+1))
    continue
  fi

  # Discover portal ID and send keepalive
  portal_id=$(discover_portal_id "${ip}")
  if [ -n "${portal_id}" ]; then
    send_keepalive "${ip}" "${portal_id}"
  else
    echo "WARN ${hostname} (${ip}): could not discover portal ID"
  fi

  brokers+=("${hostname}|${ip}|${portal_id}")
  echo "OK ${hostname} (${ip}) portal=${portal_id:-unknown}"
  added=$((added+1))
done < "${LIST}"

# Generate telegraf config
PROCESSOR_SCRIPT="${EDGE_DIR}/telegraf/processors/victron_mqtt.star"

tmp_file="$(mktemp)"
{
  echo "# Auto-generated by refresh_gx_mqtt_sources.sh. Do not edit."
  echo "# Source: ${LIST}"
  echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""

  if [ "${#brokers[@]}" -eq 0 ]; then
    echo "# No GX MQTT brokers available."
  else
    # Add starlark processor for semantic metric names
    if [ -f "${PROCESSOR_SCRIPT}" ]; then
      cat <<EOF
# Transform Victron MQTT topics into semantic metric names
[[processors.starlark]]
  namepass = ["mqtt_consumer*"]
  source = '''
$(cat "${PROCESSOR_SCRIPT}")
'''

EOF
    fi

    for entry in "${brokers[@]}"; do
      IFS='|' read -r system_id ip portal_id <<< "${entry}"
      cat <<EOF
[[inputs.mqtt_consumer]]
  servers = ["tcp://${ip}:1883"]
  topics = ["N/${portal_id:-+}/#"]
  qos = 0
  connection_timeout = "5s"
  client_id = "ovr-${system_id}"
  data_format = "json"
  topic_tag = "topic"
  [inputs.mqtt_consumer.tags]
    system_id = "${system_id}"
    gx_host = "${ip}"
    portal_id = "${portal_id:-unknown}"

EOF
    done
  fi
} > "${tmp_file}"

mv "${tmp_file}" "${OUT_FILE}"
chmod 0644 "${OUT_FILE}"

echo "SUMMARY: added=${added} skipped=${skipped} -> ${OUT_FILE}"
