# Production/release compose for EDGE nodes.
#
# Goal: "build once, deploy many".
# - Internal services are pulled from GHCR pinned by EDGE_VERSION.
# - Third-party dependencies MUST be pinned per edge release (avoid :latest).
#
# Usage on a node:
#   cd /opt/ovr/edge
#   # First-time: create /etc/ovr/edge.env (or copy from example) and link .env
#   sudo mkdir -p /etc/ovr
#   sudo cp edge.env.example /etc/ovr/edge.env
#   sudo ln -sf /etc/ovr/edge.env .env
#   # Then:
#   docker compose -f compose.release.yml pull
#   docker compose -f compose.release.yml up -d

services:
  victoria-metrics:
    image: ${VM_IMAGE:?Set VM_IMAGE in .env (symlink to /etc/ovr/edge.env; pin by tag or digest; no latest tag)}
    container_name: victoria-metrics
    command:
      - "-storageDataPath=/storage"
      - "-retentionPeriod=${VM_RETENTION:-400d}"
      - "-httpListenAddr=:8428"
    ports:
      - "8428:8428"
    volumes:
      - /mnt/esata/victoria-metrics:/storage
    restart: unless-stopped

  node-exporter:
    image: ${NODE_EXPORTER_IMAGE:?Set NODE_EXPORTER_IMAGE in .env (symlink to /etc/ovr/edge.env; pin by tag or digest; no latest tag)}
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      default:
        aliases:
          - node_exporter

  vmagent:
    image: ${VMAGENT_IMAGE:?Set VMAGENT_IMAGE in .env (symlink to /etc/ovr/edge.env; pin by tag or digest; no latest tag)}
    container_name: vmagent
    depends_on:
      - victoria-metrics
    env_file:
      - .env
    entrypoint:
      - /bin/sh
      - /entrypoint.sh
    ports:
      - "8429:8429"
    volumes:
      - ./vmagent/entrypoint.sh:/entrypoint.sh:ro
      - /etc/ovr/vmagent.scrape.yml:/etc/vmagent/scrape.yml:ro
      - /etc/ovr/targets.yml:/etc/ovr/targets.yml:ro
      - /etc/ovr/stream_aggr.yml:/etc/ovr/stream_aggr.yml:ro
      - /etc/ovr/remote_write_local_relabel.yml:/etc/ovr/remote_write_local_relabel.yml:ro
      - /etc/ovr/remote_write_cloud_relabel.yml:/etc/ovr/remote_write_cloud_relabel.yml:ro
      - /etc/ovr/secrets:/etc/ovr/secrets:ro
      - vmagent_tmp:/tmp/vmagent
    restart: unless-stopped

  grafana:
    image: ${GRAFANA_IMAGE:?Set GRAFANA_IMAGE in .env (symlink to /etc/ovr/edge.env; pin by tag or digest; no latest tag)}
    container_name: grafana
    depends_on:
      - victoria-metrics
    env_file:
      - .env
    entrypoint:
      - /bin/sh
      - /entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/entrypoint.sh:/entrypoint.sh:ro
      - grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    restart: unless-stopped

  telegraf:
    image: ${TELEGRAF_IMAGE:?Set TELEGRAF_IMAGE in .env (symlink to /etc/ovr/edge.env; pin by tag or digest; no latest tag)}
    container_name: telegraf
    depends_on:
      - victoria-metrics
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /etc/ovr/telegraf.d:/etc/telegraf/telegraf.d:ro
    command:
      - telegraf
      - --config
      - /etc/telegraf/telegraf.conf
      - --config-directory
      - /etc/telegraf/telegraf.d
      - --watch-config
      - poll

  events:
    image: ghcr.io/${GHCR_OWNER:?Set GHCR_OWNER in .env}/edge-events:${EDGE_VERSION:-dev}
    container_name: events
    depends_on:
      - victoria-metrics
    ports:
      - "127.0.0.1:8088:8088"
    volumes:
      - event_data:/data
      - /etc/ovr/secrets:/etc/ovr/secrets:ro
    env_file:
      - .env
    environment:
      - DB_PATH=/data/events.db
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - APP_VERSION=${EDGE_VERSION:-dev}
      - GIT_SHA=${EDGE_GIT_SHA:-}
    restart: unless-stopped

  frontend:
    image: ghcr.io/${GHCR_OWNER:?Set GHCR_OWNER in .env}/edge-frontend:${EDGE_VERSION:-dev}
    container_name: frontend
    depends_on:
      - events
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  vmdata:
  grafana:
  vmagent_tmp:
  event_data:
